Fixed properly checking club_committee status
SWAuk/plg_swa_viewlevels pull request #2
Opened 2016-11-08 15:24 UTC by oshotton

Fixes #1

2016-11-09 16:20 UTC, addshore requested changes

2016-11-09 16:20 UTC, addshore commented on src/viewlevels.php
> +		if( is_object( $member ) && $member->club_committee && $member->club_committee ){
Dont need to do $member->club_committee && $member->club_committee twice here

2016-11-11 18:14 UTC, addshore commented
When you deploy this will you change all empty and NULL values to be 0?

2016-11-11 18:28 UTC, oshotton commented
Already done for fix 165 on the com_sea repo:
https://github.com/SWAuk/com_swa/pull/165

2016-11-11 18:54 UTC, merged